Repository nestdotland/eggs, pull requests merged in 2020-09, with the labels that each got.

#72 deno 1.4
  .github/workflows/ship.yml
  deps.ts
  mod.ts
  src/api/post.ts
  src/commands/info.ts
  src/commands/init.ts
  src/commands/install.ts
  src/commands/link.ts
  src/commands/publish.ts
  src/commands/update.ts
  src/commands/upgrade.ts
  src/context/config.ts
  src/context/files.ts
  src/context/ignore_test.ts
  src/log.ts
  src/module.ts
  src/types.ts
  src/utilities/json.ts
Labels: priority: high, status: help wanted, type: bugfix

#75 "extends" keyword in .eggignore & pattern format
  deps.ts
  src/commands/publish.ts
  src/context/context.ts
  src/context/ignore.ts
  src/context/ignore_test.ts
Labels: type: bugfix, type: feature

#74 Remove egg.json & .eggignore
  .eggignore
  .github/workflows/ship.yml
  .gitignore
  egg.json
  src/commands/publish.ts
Labels: type: chore

#79 config
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/documentation_issue.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/workflows/test.yml
  README.md
  deps.ts
  src/commands/publish.ts
  src/context/config.ts
  src/context/context.ts
  src/context/files.ts
  src/log.ts
  src/types.ts
  src/version/version.ts
Labels: semver: patch, type: bugfix, type: feature

#82 Can't link API key on Windows
  .github/workflows/test.yml
  src/environment.ts
Labels: type: bugfix

#83 Hotfixes (merge this before 0.2.3)
  src/commands/publish.ts
  src/context/ignore.ts
Labels: type: bugfix

#84 Typo in release workflow
  .github/workflows/ship.yml
Labels: meta: ci, type: bugfix

#85 Add Drake — a task runner for Deno
  .eggignore
  .github/workflows/lint.yml
  .github/workflows/ship.yml
  .github/workflows/test.yml
  Drakefile.ts
  mod.ts
  src/api/common.ts
  src/api/fetch.ts
  src/api/module.ts
  src/api/module_test.ts
  src/commands/info.ts
  src/commands/init.ts
  src/commands/install.ts
  src/commands/link.ts
  src/commands/publish.ts
  src/commands/update.ts
  src/commands/upgrade.ts
  src/keyfile.ts
  src/utilities/environment.ts
  src/utilities/log.ts
  src/utilities/types.ts
  src/version.ts
  src/version/printVersion.ts
  src/version/version.ts
Labels: meta: ci, meta: linting, meta: tests

#88 Remove deprecated features + new way to publish
  Drakefile.ts
  README.md
  eggs.ts
  mod.ts
  src/commands/info.ts
  src/commands/init.ts
  src/commands/install.ts
  src/commands/link.ts
  src/commands/publish.ts
  src/commands/update.ts
  src/commands/upgrade.ts
  src/context/config.ts
  src/utilities/log.ts
Labels: type: bugfix, type: feature

#89 Init command update
  .github/CODE_OF_CONDUCT.md
  .github/CONTRIBUTING.md
  .github/PULL_REQUEST_TEMPLATE/pull_request.md
  CHANGELOG.md
  Drakefile.ts
  README.md
  deps.ts
  src/commands/init.ts
  src/commands/publish.ts
  src/context/config.ts
  src/context/context.ts
  src/context/ignore.ts
  src/schema.json
  src/utilities/types.ts
Labels: aspect: accessibility, type: feature

#90 Add update notification
  .github/CONTRIBUTING.md
  .github/workflows/ship.yml
  .github/workflows/test.yml
  README.md
  deps.ts
  eggs.ts
  mod.ts
  src/commands/install.ts
  src/commands/update.ts
  src/commands/upgrade.ts
Labels: type: feature
