Repository nestdotland/eggs, pull requests merged in 2020-07, with the labels that each got.

#30 feat: eggignore
  .eggignore
  .gitkeep
  deps.ts
  egg.json
  src/api/fetch.ts
  src/api/post.ts
  src/commands/init.ts
  src/commands/publish.ts
  src/context/config.ts
  src/context/config_test.ts
  src/context/context.ts
  src/context/ignore.ts
  src/context/ignore_test.ts
  src/module.ts
Labels: aspect: metadata, component: eggs, priority: medium, semver: minor, type: feature

#34 chore: update github actions
  .github/release-template.yml
  .github/workflows/ci.yml
  .github/workflows/eggs-test-deno-nightly.yml
  .github/workflows/lint.yml
  .github/workflows/ship.yml
  .github/workflows/test.yml
Labels: meta: ci

#32 Enhanced logger
  .eggignore
  .gitignore
  deps.ts
  mod.ts
  src/commands.ts
  src/commands/init.ts
  src/commands/install.ts
  src/commands/link.ts
  src/commands/publish.ts
  src/commands/update.ts
  src/commands/upgrade.ts
  src/global_module.ts
  src/log.ts
Labels: aspect: UI/UX/styling, type: feature

#37 --bump & --version in eggs publish
  deps.ts
  src/commands/publish.ts
  src/log.ts
Labels: type: feature

#33 Init command default options
  README.md
  src/commands/init.ts
Labels: type: bugfix

#47 Install command was broken
  deps.ts
  src/commands/install.ts
  src/commands/update.ts
  src/commands/upgrade.ts
  src/global_module.ts
Labels: type: bugfix

#48 bump version to 0.2.0
  README.md
  src/commands/publish.ts
  src/commands/update.ts
  src/version.ts
Labels: semver: N/A, type: chore

#51 0.2.1
  README.md
  egg.json
  src/version.ts
Labels: semver: patch
