Repository nestdotland/eggs, pull requests merged in 2020-10, with the labels that each got.

#91 Confirmation for staged files
  Drakefile.ts
  benchmarks/commands/update/deps.ts
  deps.ts
  eggs.ts
  src/commands/info.ts
  src/commands/install.ts
  src/commands/publish.ts
  src/commands/upgrade.ts
  src/context/config.ts
  src/context/config_test.ts
  src/utilities/log.ts
  test/deps.ts
Labels: hacktoberfest-accepted, type: feature

#92 Entry file was duplicated in the files field after publication
  src/api/fetch.ts
  src/api/post.ts
  src/commands/init.ts
  src/commands/publish.ts
  src/commands/update.ts
  src/context/files.ts
  src/context/ignore_test.ts
  src/utilities/log.ts
Labels: type: bugfix

#95 Rename cli options (breaking changes)
  Drakefile.ts
  README.md
  deps.ts
  src/commands/init.ts
  src/commands/publish.ts
  src/context/config.ts
  src/context/ignore_test.ts
Labels: hacktoberfest-accepted, type: chore

#97 0.3.0
  .eggignore
  .github/CODE_OF_CONDUCT.md
  .github/CONTRIBUTING.md
  .github/PULL_REQUEST_TEMPLATE/pull_request.md
  .github/workflows/lint.yml
  .github/workflows/ship.yml
  .github/workflows/test.yml
  CHANGELOG.md
  Drakefile.ts
  README.md
  benchmarks/commands/update/deps.ts
  deps.ts
  eggs.ts
  mod.ts
  src/api/common.ts
  src/api/fetch.ts
  src/api/module.ts
  src/api/module_test.ts
  src/api/post.ts
  src/commands/info.ts
  src/commands/init.ts
  src/commands/install.ts
  src/commands/link.ts
  src/commands/publish.ts
  src/commands/update.ts
  src/commands/upgrade.ts
  src/context/config.ts
  src/context/config_test.ts
  src/context/context.ts
  src/context/files.ts
  src/context/ignore.ts
  src/context/ignore_test.ts
  src/keyfile.ts
  src/schema.json
  src/utilities/environment.ts
  src/utilities/log.ts
  src/utilities/types.ts
  src/version.ts
  src/version/printVersion.ts
  src/version/version.ts
  test/deps.ts
Labels: semver: minor

#99 Entry file & eggignore ./
  src/commands/publish.ts
  src/context/files.ts
  src/context/ignore_test.ts
  src/version.ts
Labels: type: bugfix

#100 0.3.1
  src/commands/publish.ts
  src/context/files.ts
  src/context/ignore_test.ts
  src/version.ts
Labels: semver: patch
